#! /usr/bin/env bash

branch=$(git branch --show-current)

if [ "$branch" = staging ]
then
  if [ -z "$(git status --porcelain)" ]
  then
    echo staging.coleandlopez.com > CNAME
    if [ -z "$(git status --porcelain)" ]
    then
      git commit -am "fix CNAME (automatic commit by deploy script)"
    fi
    git push staging staging
    echo your changes will soon appear at staging.coleandlopez.com
  else
    echo git tree must be clean
    exit 1
  fi
else
  echo must be on branch '"staging"'
  exit 1
fi
