#! /usr/bin/env bash

set -eu

branch=$(git branch --show-current)

if [ "$branch" = master ]
then
  if [ -z "$(git status --porcelain)" ]
  then
    if [ ! -e CNAME ]
    then
      touch CNAME
      echo "www.coleandlopez.com" > CNAME
      git commit -am "adding CNAME (automatic commit from deploy script)"
    fi
    git push origin master
    echo your changes will soon appear at https://www.coleandlopez.com
  else
    echo git tree must be clean
    exit 1
  fi
else
  echo must be on branch '"master"'
  exit 1
fi
