backend:
  name: git-gateway
  branch: staging
media_folder: 'cms-media'
collections:
  - name: 'gallery-image' # Used in routes, e.g., /admin/collections/blog
    label: 'Gallery Image' # Used in the UI
    folder: 'src/cms/gallery-images' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: json
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
  - name: 'main-sections'
    label: 'Main Section'
    folder: 'src/cms/main-sections'
    create: true
    extension: json
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Title Background Image', name: 'title-background-image', widget: 'image' }
      - {
          label: 'Title Background Image Alt Text',
          name: 'title-background-image-alt-text',
          widget: 'string',
        }
      - { label: 'Section Body', name: 'section-body-markdown', widget: 'markdown' }
